events {}

http {
    resolver 127.0.0.11 valid=10s;

    server {
        listen 80;
        server_name app.local;
        return 301 https://$host$request_uri;
        }

    server {
        listen 443 ssl;
        server_name app.local;
        
        ssl_certificate     /etc/nginx/certs/app.local.crt;
        ssl_certificate_key /etc/nginx/certs/app.local.key;

        location / {
            set $backend_upstream backend-blue:8000;
            proxy_pass http://$backend_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
