name: Deploy Backend

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: [self-hosted]
    steps:
      - name: Pull latest code
        run: |
          cd /home/jahongir/devops-backend
          git pull origin main

      - name: Run deploy.sh
        run: |
          cd /home/jahongir/devops-backend
          ./deploy.sh
